spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/chatdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    database: mysql

    # InnoDB setting
    # InnoDB? DB engine that supports transactions
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true